### ISSUE TITLE
How to run this application?

### ISSUE THREAD

**Issue by NikasZalias** [IsmailYC/Speaker-Recognition-with-GUI#1]
Hi,

I want to run this neural network. In main directory I create folder "Train" and added few .wav files. When I run GUI, I select that folder as data folder, then select MFCC, delta and delta delta checkboxes and press train button. Then I get these errors:

> Error using audioread (line 74)
The filename specified was not found in the MATLAB path.
Error in PrepareData (line 2)
[~,fs]=audioread([directory,'\1\Track (1).wav']);
Error in NetworkBuildTrainGUI/TrainButtonCallback (line 319)
            [data,target,fs]= PrepareData(SpeechDirectory,SpeakerName,TrackName,FrameWidth,FrameInc,Persons,Tracks,SelectedFeatures,FeaturesNbr);
Error while evaluating UIControl Callback

how to run this network without errors?

**Comment by IsmailYC** [comment]
Hi,

So about the directory It's not customizable yet. So the folder name and file name fields don't serve any purpose right now. So if you want to run it without errors your directory should contain folders named 1,2,3,.... and within each folder the audio files should be named Track (1).wav, Track (2).wav, ....

**Comment by NikasZalias** [comment]
Thanks, I'll try to do it like this and tell if it was successful. :)

**Comment by IsmailYC** [comment]
okay and feel free to contact me here or on my facebook. 👍

**Comment by NikasZalias** [comment]
Contacted you on facebook

**Comment by NikasZalias** [comment]
It's still does not work... Program throws the same error
